kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: blinkt-k8s-controller
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        name: blinkt-k8s-controller
    spec:
      serviceAccountName: blinkt-k8s-controller-sa
      containers:
      - name: blinkt-k8s-controller
        image: apprenda/blinkt-k8s-controller:v1
        env:
        - name: COLOR
          value: "#000B87"
        - name: NAMESPACE
          value: default
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - mountPath: /sys
          name: sys-tree
      volumes:
      - name: sys-tree
        hostPath:
          path: /sys
